### ISSUE TITLE
dnsmasq: process is missing required capability NET_ADMIN

### ISSUE THREAD

**Issue by raugusti** [ferrarimarco/docker-pxe#107]
Is this a bug related to new docker-ce version?

**Comment by ferrarimarco** [comment]
Hi! How are you running the container image? You may beed to add the `NET_ADMIN`  when running it :)

**Comment by DeividLegion** [comment]
> Hi! How are you running the container image? You may beed to add the `NET_ADMIN` when running it :)

HOW?
I am completely lost on how you add NET_ADMIN when pressing run.

**Comment by yanarof** [comment]
> HOW? I am completely lost on how you add NET_ADMIN when pressing run.

with `docker run --cap-add=NET_ADMIN ...` [source](https://stackoverflow.com/questions/58377469/difference-between-cap-add-net-admin-and-add-capabilities-in-yml)
