### ISSUE TITLE
Unable to run on RaspberryPi/Docker

### ISSUE THREAD

**Issue by techbytesrn** [ferrarimarco/docker-pxe#27]
Trying to run this and it stops at the following line -
dnsmasq-tftp: TFTP root is /var/lib/tftpboot 

Also tried running it with this line - 
docker run -it --rm --net=host  ferrarimarco/pxe --dhcp-range=10.0.1.1,proxy

Are there other files/services I should have installed ?
New to docker and have been able to get other containers to run
Suggestions on how to troubleshoot this one ?

Thanks,
Ron

**Comment by ferrarimarco** [comment]
Hi @techbytesrn ! Can you post the full output?

Have Docker installed is enough :)

**Comment by techbytesrn** [comment]
Marco:

I have setup a new RPI host with only docker and portainer running on it.
Here is the screen output when I try to install PXE -

pi@raspberrypi:~ $ docker run -it --rm --net=host  ferrarimarco/pxe
--dhcp-range=10.0.1.1,proxy
Unable to find image 'ferrarimarco/pxe:latest' locally
latest: Pulling from ferrarimarco/pxe
3a2c5e3c37b2: Pull complete
bfc4b12081ca: Pull complete
2292bbfc8dee: Pull complete
6120d6d26f82: Pull complete
952056b7f891: Pull complete
44a8282c69eb: Pull complete
081a28afbff4: Pull complete
Digest:
sha256:809554eb90ae72fdaf67ee5da9a7b5e89a49fc7e43633029751e898dcd664e87
Status: Downloaded newer image for ferrarimarco/pxe:latest
dnsmasq: started, version 2.80 DNS disabled
dnsmasq: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP
DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
dumpfile
dnsmasq-dhcp: DHCP, proxy on subnet 10.0.1.1
dnsmasq-tftp: TFTP root is /var/lib/tftpboot

The output stops at this point and does not return to the command prompt.
I thought the problem I was having was due to the Ubiquiti management
server running on the docker host using a configuration I hadnt see before.
What I have setup is as a "generic" an install as I would think.
My end goal is to have several RPI's running different containers with some
of the smart home tech I am covering for my YouTube channel.

Would appreciate any insight that you can provide.
I am happy to provide any logs or other info that you may request.

Thanks,
Ron

**Comment by ferrarimarco** [comment]
The container is running as you can see from the logs. If you want to run it in background, just [enable detached mode](https://docs.docker.com/engine/reference/run/#detached-vs-foreground).
