### ISSUE TITLE
Info on adding menu item

### ISSUE THREAD

**Issue by docop** [ferrarimarco/docker-pxe#51]
Hi  I try for a while and find your image that do boot direct over lan and go to the memtest. This is nice and working.. but how to add a custom os ?
 i run with : docker run --cap-add=NET_ADMIN -it --rm --net=host ferrarimarco/pxe --dhcp-range=192.168.48.8,192.168.48.14,255.255.255.240

For a menu:
LABEL Fatdog64
  MENU LABEL Fatdog64 liveos
  KERNEL /Fatdog64/casper/vmlinuz
  APPEND initrd=Fatdog64/casper/initrd auto=true interface=eth0 ip=dhcp url=http://192.168.48.10/Fatdog64-812.iso

While with netboot.xyz i did download the live image: vmlinuz and initrd .. i'm not sure how to put it into your app. And as with an .iso file.. i see option like :  
mkdir fatdog64
mount -o loop Fatdog64-812.iso fatdog64

 But where did the mount need to be place and how to set into your soft. Was it to run the docker with  -d  and go into the running process and change a file.. Or set a  -v option to tell where the 'assets'  or iso are present ..

Thanks in advance

**Comment by ferrarimarco** [comment]
Hi! Here's an example: https://github.com/ferrarimarco/docker-pxe#additional-pxe-boot-menu-entries

To make the image file available, I'd either mount a volume from the host or bake it into the image as you build it.
