### ISSUE TITLE
UEFI boot

### ISSUE THREAD

**Issue by Lueton** [ferrarimarco/docker-pxe#82]
Hey! Im trying to use this image for booting my Optiplex micro, which to my information only supports UEFI Grub. Is it possible to configure this image to work with UEFI?  
Thanks :)

**Comment by ferrarimarco** [comment]
Hi! I think you may want to have a look at dnsmasq docs, and find a proper image to boot. There should be nothing that prevents this container image that prevents supporting UEFI boots. :)

**Comment by peedy2495** [comment]
Normally, you have to use shim and a linked grubnetx64.efi to grubx64.efi if u're using a http source for starting images from your webserver.
You can take a look on my related Project: https://github.com/peedy2495/DockerPXE-OS-Automation
Thanks to ferrarimarco for providing this docker-image ;-)
